// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUJwsmQ2ZfG02KfDw0_R_sOamrjWu33H0',
    appId: '1:725811688161:web:8ae2c04c7ce7fc17213da0',
    messagingSenderId: '725811688161',
    projectId: 'sos-guardian-22ba2',
    authDomain: 'sos-guardian-22ba2.firebaseapp.com',
    databaseURL: 'https://sos-guardian-22ba2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sos-guardian-22ba2.firebasestorage.app',
    measurementId: 'G-ZQ8916NLQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo2GVtl9OcjxxrOUMD2LcdPosRdKqb90s',
    appId: '1:725811688161:android:296774682a8830ef213da0',
    messagingSenderId: '725811688161',
    projectId: 'sos-guardian-22ba2',
    databaseURL: 'https://sos-guardian-22ba2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sos-guardian-22ba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4e_9xWfYhGQfmPQcu_ZDU0OS31Yoj28s',
    appId: '1:725811688161:ios:54d6cd883846abbb213da0',
    messagingSenderId: '725811688161',
    projectId: 'sos-guardian-22ba2',
    databaseURL: 'https://sos-guardian-22ba2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sos-guardian-22ba2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4e_9xWfYhGQfmPQcu_ZDU0OS31Yoj28s',
    appId: '1:725811688161:ios:54d6cd883846abbb213da0',
    messagingSenderId: '725811688161',
    projectId: 'sos-guardian-22ba2',
    databaseURL: 'https://sos-guardian-22ba2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sos-guardian-22ba2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUJwsmQ2ZfG02KfDw0_R_sOamrjWu33H0',
    appId: '1:725811688161:web:62c3e7bc47c44fd0213da0',
    messagingSenderId: '725811688161',
    projectId: 'sos-guardian-22ba2',
    authDomain: 'sos-guardian-22ba2.firebaseapp.com',
    databaseURL: 'https://sos-guardian-22ba2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sos-guardian-22ba2.firebasestorage.app',
    measurementId: 'G-Y0PEL32X1G',
  );
}
